#!/bin/bash

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << FDISK_CMDS  | fdisk /dev/sda
g 
n      
1      
       
+128M 

n      
2      
        
+512M  
n
3

     
t      
1      
1     
t      
2      
19     
w      
FDISK_CMDS
mkfs.fat -F 32 /dev/sda1
mkfs.ext4 /dev/sda3
mkswap /dev/sda2
swapon /dev/sda2
mount /dev/sda3 /mnt/gentoo
cd /mnt/gentoo
wget https://distfiles.gentoo.org/releases/amd64/autobuilds/20230813T170146Z/stage3-amd64-desktop-openrc-20230813T170146Z.tar.xztar xpvf stage3-amd64-desktop-openrc-20230806T163139Z.tar.xz
nano -w /mnt/gentoo/etc/portage/make.conf
mirrorselect -i -o >> /mnt/gentoo/etc/portage/make.conf
mkdir --parents /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
cp --dereference /etc/resolv.conf /mnt/gentoo/etc/
mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --bind /run /mnt/gentoo/run
mount --make-slave /mnt/gentoo/run
echo 'Now, type these commands:
chroot /mnt/gentoo /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"
wget https://raw.githubusercontent.com/MartinoDiVietro/Gentoo/main/Gentoo1
chmod +x Gentoo1
./Gentoo1
'















































































