#!/bin/bash

cd /etc/portage/package.use
touch nautilus
echo "gnome-base/nautilus -previewer" >> nautilus
nano /etc/portage/make.conf
USE="minimal" emerge --ask --oneshot libsndfile
emerge --ask gnome-base/gnome
env-update && source /etc/profile
getent group plugdev
gpasswd -a martino plugdev
rc-update add elogind boot
rc-service elogind start
emerge --ask --noreplace gui-libs/display-manager-init
nano /etc/conf.d/display-manager
rc-update add display-manager default 
rc-service display-manager start  

